import keyword
f = str("for")
p = str("print")
br = str("break")
d = str("done")
b = str("bad")
print(keyword.iskeyword(f),f)
print(keyword.iskeyword(p),p)
print(keyword.iskeyword(br),br)
print(keyword.iskeyword(d),d)
print(keyword.iskeyword(b),b)